<?php

namespace Yosimitso\WorkingForumBundle\Repository;

/**
 * PostVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
